analyzer:
  errors:
    library_private_types_in_public_api: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_empty_else: true
    no_duplicate_case_values: true
    unnecessary_null_checks: true
    unnecessary_new: true
    unnecessary_this: true
    prefer_const_constructors: true
    prefer_final_locals: true
    combinators_ordering: true
    sort_pub_dependencies: true
    sort_child_properties_last: true
    sort_constructors_first: true
