name: spendwise
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  cloud_firestore: ^6.0.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  fl_chart: ^0.70.0
  flutter:
    sdk: flutter
  flutter_font_icons: ^2.2.7
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^3.0.2
  get_it: ^8.2.0
  internet_connection_checker_plus: ^2.9.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.3

dependency_overrides:
  source_gen: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - images/a_dot_burr.jpeg
